[garden]
description = "A garden where plants and animals can live"

[garden.fields]
name = { type = "str" }
width = { type = "int" }
height = { type = "int" }

[garden_tile]
description = "A single tile in the garden occupied by a sprite"

[garden_tile.fields]
garden = { type = "relation", schema = { name = "garden" } }
pos_x = { type = "int" }
pos_y = { type = "int" }
sprite = { type = "pinned_relation", schema = { name = "garden_sprite" } }
timestamp = { type = "int" }

[garden_sprite]
description = "An item that can be placed in the garden"

[garden_sprite.fields]
img = { type = "relation", schema = { id = "blob_v1" } }
description = { type = "str" }